---
env:
  name: UAM-v0
  max_episode_steps: 250
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    N_agents: 5
  info: ''
agent:
  MADDPG: {}
  MATD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
seed: 42
timesteps: 100_000_000
epoch_length: 5000
eval_episodes: 10
actor_weights:
critic_weights:
gamma: 0.99
tau: 0.01
net_struc_actor:
- - 64
  - relu
- - 64
  - relu
- tanh
net_struc_critic:
- - 64
  - relu
- - 64
  - relu
- identity
optimizer: Adam
loss: MSELoss
lr_actor: 0.01
lr_critic: 0.01
buffer_length: 1_000_000
grad_rescale: false
grad_clip: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 100
batch_size: 1024
device: cpu
