---
env:
  name: UAM-Modular-Validation-v0
  max_episode_steps: 100_000
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    situation: 1
    sim_study: True
    sim_study_N: 30
    safe_number: 0
    entry_check: False
  info: ''
agent:
  LSTMRecTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
    num_obs_OS: 3
    num_obs_TS: 6
seed: 42
timesteps: 3_000_000
epoch_length: 5000
eval_episodes: 1
actor_weights: LSTMRecTD3_actor_weights.pth
critic_weights: LSTMRecTD3_critic_weights.pth
gamma: 0.99
tau: 0.001
net_struc_actor: 
net_struc_critic: 
optimizer: Adam
loss: MSELoss
lr_actor: 0.0001
lr_critic: 0.0001
buffer_length: 500_000
grad_rescale: false
grad_clip: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 1
batch_size: 32
device: cpu
